services:
  mysql:
    image: mysql:8
    container_name: userage-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userage_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    container_name: userage-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: userage_db

  frontend:
    build: ./userage_mern
    container_name: userage-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mysql_data:
